{
 "title": "Unbound",
 "description": "all unbound metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(unbound_hits_queries,instance)"
    }
   },
   {
    "name": "interval",
    "query": "15s,30s,1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "thread",
    "query": {
     "query": "label_values(unbound_hits_queries{instance=\"$instance\"},type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overall stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queries in / out over time",
   "type": "timeseries",
   "description": "Queries in +  \n\nQueries out - ",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg_over_time(unbound_hits_queries{instance=\"$instance\", type=~\"total.num.queries|total.num.cachehits\"}[$interval])",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "avg_over_time(unbound_entries_expired{instance=\"$instance\", type=~\"total.num.expired\"}[$interval])",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "avg_over_time(unbound_hits_queries{instance=\"$instance\", type=~\"num.query.udpout|total.num.prefetch|num.query.tcpout\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Total queries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum_over_time(unbound_hits_queries{instance=\"$instance\", type=\"total.num.queries\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "avg query rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "r/s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expression": "$A / (${__to:date:seconds} - ${__from:date:seconds})",
     "type": "math"
    }
   ]
  },
  {
   "title": "avg cache hit ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 / avg_over_time(unbound_hits_queries{instance=\"$instance\", type=\"total.num.queries\"}[$__interval]) * ignoring(type) avg_over_time(unbound_hits_queries{instance=\"$instance\", type=\"total.num.cachehits\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "timeseries",
   "description": "Percentage of queries that could be answered from cache",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 / avg_over_time(unbound_hits_queries{instance=\"$instance\", type=\"total.num.queries\"}[$interval]) * ignoring(type) avg_over_time(unbound_hits_queries{instance=\"$instance\", type=\"total.num.cachehits\"}[$interval])",
     "legendFormat": "cachefactor"
    }
   ]
  },
  {
   "title": "Total queries UDP out",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum_over_time(unbound_hits_queries{instance=\"$instance\", type=\"num.query.udpout\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total queries tcp out",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum_over_time(unbound_hits_queries{instance=\"$instance\", type=\"num.query.tcpout\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total: A",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum_over_time(unbound_by_type_queries{instance=\"$instance\", type=\"A\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total: AAAA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum_over_time(unbound_by_type_queries{instance=\"$instance\", type=\"AAAA\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total: SVR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum_over_time(unbound_by_type_queries{instance=\"$instance\", type=\"SRV\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total: PTR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum_over_time(unbound_by_type_queries{instance=\"$instance\", type=\"PTR\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "recursive queries responsetime heatmap",
   "type": "heatmap",
   "description": "This does not count cached responses  \n  \nEvery element counts the recursive queries whose reply time fit between the lower and upper  bound.   Times  larger  or  equal  to the lowerbound, and smaller than the upper bound.  There are 40 buckets, with bucket sizes doubling.",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "unbound_histogram_seconds{instance=\"$instance\", bucket=~\"0.000000.to.0.000001|0.000001.to.0.000002|0.000002.to.0.000004|0.000004.to.0.000008|0.000008.to.0.000016|0.000016.to.0.000032|0.000032.to.0.000064|0.000064.to.0.000128|0.000128.to.0.000256|0.000256.to.0.000512|0.000512.to.0.001024|0.001024.to.0.002048|0.002048.to.0.004096|0.004096.to.0.008192|0.008192.to.0.016384|0.016384.to.0.032768|0.032768.to.0.065536|0.065536.to.0.131072|0.131072.to.0.262144|0.262144.to.0.524288|0.524288.to.1.000000|1.000000.to.2.000000|2.000000.to.4.000000|4.000000.to.8.000000|8.000000.to.16.000000|16.000000.to.32.000000|32.000000.to.64.000000|128.000000.to.256.000000\"}",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "memory usage over time",
   "type": "timeseries",
   "description": "rrset=domain/ip-pair  \nmessage=complete DNS response",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sort_desc(unbound_memory_bytes{instance=\"$instance\", type=~\"mem.cache.rrset|mem.cache.message\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "bargauge",
   "description": "rrset=domain/ip-pair  \n  \nmessage=complete DNS response",
   "gridPos": { "h": 7, "w": 3, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(unbound_memory_bytes{instance=\"$instance\", type=~\"mem.cache.message|mem.cache.rrset\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Total: MX",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum_over_time(unbound_by_type_queries{instance=\"$instance\", type=\"MX\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total: TXT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum_over_time(unbound_by_type_queries{instance=\"$instance\", type=\"TXT\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query by type",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum_over_time(unbound_by_type_queries{instance=\"$instance\"}[$__interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Number of cached entries over time",
   "type": "timeseries",
   "description": "rrset=domain/ip-pair  \nmessage=complete DNS response",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 23 },
   "targets": [
    {
     "expr": "sort_desc(unbound_memory_bytes{instance=\"$instance\", type=~\"rrset.cache.count|msg.cache.count\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Total entries in cache",
   "type": "bargauge",
   "description": "rrset=domain/ip-pair  \nmessage=complete DNS response",
   "gridPos": { "h": 7, "w": 3, "x": 17, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(unbound_memory_bytes{instance=\"$instance\", type=~\"msg.cache.count|rrset.cache.count\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Recursion avg",
   "type": "timeseries",
   "description": "recursion.time.avg  \n  \nAverage time it took to answer  queries  that  needed  recursive processing.  Note that queries that were answered from the cache are not in this average.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(unbound_query_recursion_time_avg{instance=\"$instance\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Requestlist",
   "type": "timeseries",
   "description": "Requestlist can be understood as the requestqueue\n  \n\nrequestlist.avg  \n-The  average  number  of requests in the internal recursive processing request list on insert of a new incoming recursive  processing query.  \n  \nrequestlist.max  \n-Maximum  size  attained by the internal recursive processing request list.  \n  \nrequestlist.overwritten  \n-Number of requests in the request list that were overwritten  by newer  entries. This happens if there is a flood of queries that recursive processing and the server has a hard time.  \n  \nrequestlist.exceeded  \n-Queries that were dropped because the  request  list  was  full. This  happens  if  a flood of queries need recursive processing, and the server can not keep up.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "avg_over_time(unbound_queue_queries{instance=\"$instance\", type=~\"total.requestlist.*\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Recursion median",
   "type": "timeseries",
   "description": "recursion.time.median  \n  \nThe median of the time it took to answer queries that needed recursive  processing.   The  median  means  that  50% of the user queries were answered in less than this time.   Because  of  big\noutliers  (usually queries to non responsive servers), the average can be bigger than the median.  This median has been  calculated by interpolation from a histogram.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(unbound_query_recursion_time_median{instance=\"$instance\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Queries by type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "avg_over_time(unbound_by_type_queries{instance=\"$instance\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Per thread stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Queries over time ${thread}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "repeat": "thread",
   "targets": [
    {
     "expr": "avg_over_time(unbound_hits_queries{instance=\"$instance\", type=~\"${thread}.num.*\"}[$interval])",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "avg_over_time(unbound_entries_expired{instance=\"$instance\", type=~\"${thread}.num.expired\"}[$interval])",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "avg_over_time(unbound_hits_prefetch{instance=\"$instance\", type=~\"${thread}.num.prefetch\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate ${thread}",
   "type": "timeseries",
   "description": "Percentage of queries that could be answered from cache",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "repeat": "thread",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 / avg_over_time(unbound_hits_queries{instance=\"$instance\", type=~\"${thread}.num.queries\"}[$interval]) * ignoring(type) avg_over_time(unbound_hits_queries{instance=\"$instance\", type=~\"${thread}.num.cachehits\"}[$interval])",
     "legendFormat": "Cachehit"
    }
   ]
  },
  {
   "title": "Recursion avg & median ${thread}",
   "type": "timeseries",
   "description": "recursion.time.avg  \n  \nAverage time it took to answer  queries  that  needed  recursive processing.  Note that queries that were answered from the cache are not in this average.\n\nrecursion.time.median  \n  \nThe median of the time it took to answer queries that needed recursive  processing.   The  median  means  that  50% of the user queries were answered in less than this time.   Because  of  big\noutliers  (usually queries to non responsive servers), the average can be bigger than the median.  This median has been  calculated by interpolation from a histogram.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "repeat": "thread",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(unbound_query_recursion_time_avg{instance=\"$instance\", type=~\"${thread}.recursion.time.avg\"}[$interval])",
     "legendFormat": "recursion ${thread} avg"
    },
    {
     "expr": "avg_over_time(unbound_query_recursion_time_median{instance=\"$instance\", type=~\"${thread}.recursion.time.median\"}[$interval])",
     "legendFormat": "recursion ${thread} median"
    }
   ]
  },
  {
   "title": "Requestlist ${thread}",
   "type": "timeseries",
   "description": "Requestlist can be understood as the requestqueue\n  \n\nrequestlist.avg  \n-The  average  number  of requests in the internal recursive processing request list on insert of a new incoming recursive  processing query.  \n  \nrequestlist.max  \n-Maximum  size  attained by the internal recursive processing request list.  \n  \nrequestlist.overwritten  \n-Number of requests in the request list that were overwritten  by newer  entries. This happens if there is a flood of queries that recursive processing and the server has a hard time.  \n  \nrequestlist.exceeded  \n-Queries that were dropped because the  request  list  was  full. This  happens  if  a flood of queries need recursive processing, and the server can not keep up.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "repeat": "thread",
   "targets": [
    {
     "expr": "avg_over_time(unbound_queue_queries{instance=\"$instance\", type=~\"${thread}.requestlist.*\"}[$interval])",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "avg_over_time(unbound_queue_overwritten{instance=\"$instance\", type=~\"${thread}.requestlist.*\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}